<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hp" failures="1" tests="1" name="com.ita.Runner.TestNGRunner" time="9.050" errors="0" timestamp="2023-04-18T22:07:36 BST" skipped="0">
  <testcase classname="com.ita.Runner.TestNGRunner" name="runScenario" time="9.050">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.ita.stepDefinitions.ViewCvs.theUserNavigatesToTheWorkExperienceTab(ViewCvs.java:52)
at âœ½.the user navigates to the Work Experience tab(file:///D:/Training/Batch2_Oct_2022/12032003/October2022Batch/src/test/java/com/ita/features/ViewCVs.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.ita.Runner.TestNGRunner -->
